spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/backapi
    username: root
    password: 1234
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 50MB
      enabled: true
      location: /Users/mogreene/Desktop/files
mogreene:
  upload:
    path: /Users/mogreene/Desktop/files/

mybatis:
  type-aliases-package: com.mogreene.board.dto
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

#mybatis 로깅 설정
logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: debug
      resultsettable: debug
      audit: off
      resultset: off
      connection: off
